// src/components/social.tsx
export default function Social() {
  return (
    <section className="flex gap-4 flex-col md:flex-row">
      <div className="flex flex-col gap-1 align-center">
        <a className="text-center bg-gray-700 py-3 px-4 rounded-xl" href="mailto:hello@iamstevendao.com">
          Say&nbsp;<span className="text-amber-100">hello@iamstevendao.com</span>
        </a>
        <span className="text-center">Want to collaborate? Let's talk!</span>
      </div>
      <a className="text-sky-500 md:py-3" href="https://github.com/sponsors/iamstevendao?ref=iamstevendao.com"
      >Become a sponsor</a>
      <a className="text-sky-500 md:py-3" href="https://github.com/iamstevendao?ref=iamstevendao.com"
      >View my projects
      </a>
    </section>
  )
}

// src/components/Social.vue
<!-- Social -->

<template>
  <section class="social container">
    <div class="social-item">
      <a class="btn btn-email block" href="mailto:hello@iamstevendao.com">
        Say <span class="highlight">hello@iamstevendao.com</span>
      </a>
      <span class="center description">Want to collaborate? Let's talk!</span>
    </div>
    <div class="social-item">
      <a class="btn" href="https://github.com/sponsors/iamstevendao?ref=iamstevendao.com"
        >Become a sponsor</a
      >
    </div>
    <div class="social-item">
      <a class="btn" href="https://github.com/iamstevendao?ref=iamstevendao.com"
        >View my projects</a
      >
    </div>
  </section>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component';

export default class Social extends Vue {
}
</script>

<style lang="scss" scoped>
.social {
  a {
    text-decoration: none;

    &.btn {
      padding: 15px;
      display: block;
    }

    &.btn-email {
      color: var(--text-color-normal);
      text-decoration: none;
      border-radius: 15px;
      margin-right: 15px;
      background-color: var(--bg-btn);
    }
  }

  .social-item {
    display: inline-block;
    vertical-align: top;
  }

  .description {
    color: var(--text-color-light);
    display: block;
    margin-top: 10px;
  }
}
</style>
